### ISSUE TITLE
Is openCV 3.2 suitable for this package? 

### ISSUE THREAD

**Issue by Ohayooooo** [angusleigh/leg_tracker#10] opened 2018-02-26 11:25 UTC
When I run catkin_make, there are some errors:

Built target extract_positive_training_clusters
/home/ohayoo/catkin_ws/src/leg_tracker/src/detect_leg_clusters.cpp: In member function ‘void DetectLegClusters::laserCallback(const ConstPtr&)’:
/home/ohayoo/catkin_ws/src/leg_tracker/src/detect_leg_clusters.cpp:213:19: error: ‘class cv::ml::RTrees’ has no member named ‘getVotes’
           forest->getVotes(cv::cvarrToMat(tmp_mat), result, 0);
                   ^
I use openCV 3.2. Is the version appropriate?

**Comment by clement91190** [comment] 2018-04-10 12:33
yes, i get the same problem. any fix ?

**Comment by angusleigh** [comment] 2018-04-21 22:56
I can't reproduce. Can you pull and try again? It might be fixed after https://github.com/angusleigh/leg_tracker/commit/e073904709dd2f54dc5291270b516e7a018f8e28

**Comment by DavidHan008** [comment] 2018-05-15 05:14
yes, i get the same problem. any fix ?

**Comment by DavidHan008** [comment] 2018-05-15 05:42
detect_leg_clusters.cpp:213:19: error: ‘class cv::ml::RTrees’ has no member named ‘getVotes’
           forest->getVotes(cv::cvarrToMat(tmp_mat), result, 0);

**Comment by DavidHan008** [comment] 2018-05-15 05:42
ubuntu14.04 ros_indigo

**Comment by angusleigh** [comment] 2018-05-22 15:58
Oh boy, I looks like [this commit](https://github.com/angusleigh/leg_tracker/commit/9e06c80829cee3027093702a08e27e051fee2c4a) is not backwards compatible to OpenCV 3.2 or earlier. Are you able to update past OpenCV 3.3? If not, I suppose a temporary, hacky solution would be to just revert that change locally in your workspace.

Ref:
This is the function we call in OpenCV 3.4: https://docs.opencv.org/3.4/d0/d65/classcv_1_1ml_1_1RTrees.html#a46cd96dee4738c07899067344efe2956
But it looks like it was newly added as it isn't in the OpenCV 3.2 docs:
https://docs.opencv.org/3.2.0/d0/d65/classcv_1_1ml_1_1RTrees.html#details

**Comment by memexiaoda** [comment] 2018-08-29 03:00
其上传的代码有误，forest.load(forest_file.c_str());
    feat_count_ = forest.get_active_var_mask()->cols;
    forest = cv::ml::StatModel::load<cv::ml::RTrees>(forest_file);
    feat_count_ = forest->getVarCount();
把源代码删掉，换成这个

**Comment by memexiaoda** [comment] 2018-08-29 03:02
how to running leg_tracker on own robot?

**Comment by angusleigh** [comment] 2018-09-30 11:23
Fixed in [5d00d51](https://github.com/angusleigh/leg_tracker/commit/5d00d51722029d98b1eb34a22cc0cddd2a8ecc2b). Try pulling and running again from head.

**Closed as completed by angusleigh** 2018-09-30 11:23 UTC

**Comment by jnisa** [comment] 2019-07-25 11:47
Anyone knows how to solve this problem for ROS Melodic in Ubuntu 18.04? My OpenCV version is 3.2.
Thanks in advance

**Comment by angusleigh** [comment] 2019-07-25 13:31
I thought 5d00d51 would fix it. Can you pull and try again? What's your error message? You might be able to try manually deleting this section of code to see if it's just the compiler directive not working properly? https://github.com/angusleigh/leg_tracker/blob/melodic/src/detect_leg_clusters.cpp#L213-L220
